### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by MSP-Greg** [jgarber/redcloth#58]
I've got passing tests on Travis for 1.9.3 thru 2.3, and Actions passing Ubuntu, macOS, & Windows  with Ruby 2.4 thru 2.7.

Not ready yet, and maybe a few questions.  Might you be interested in a new release?

JFYI, I'm a Windows guy, not a 'c type', and from various work I know enough about *nix to often be able to get things working.

**Comment by joshuasiler** [comment]
Hi! Glad to see some effort put in on the project. I am no longer actively working on this project. 

Would you be interested in taking over as the primary maintainer?

**Comment by MSP-Greg** [comment]
Sorry.  See https://github.com/jgarber/redcloth/issues/51

I work with YARD, see https://msp-greg.github.io/.  I think (?) a few of the repos doc'd there may use Textile, not sure.  YARD CI had to add a hack to get the Windows CI to run, as when the pre-compiled binaries were removed, code wasn't adjusted for it.

1. Small change to the extconf.rb code, which fixes https://github.com/jgarber/redcloth/issues/57, as I had the same problem locally.

2. Ragel on windows didn't work, but I've used it in other repos.  Adjusted the rake code, and it works everywhere.

3. I haven't yet, but I'll clean up the gemspec.

4. Maybe more things, but nothing significant.

So, I don't really know c, I'm not that familiar with Textile, and I've plenty of things to work on.

I guess if you're trying to hand off maintenance, having a release that works and has proper CI would be helpful...

**Comment by joshuasiler** [comment]
I'm unlikely to have any time to validate your work. If you want to become a maintainer, push a new release, and that's all you do that'd be a step forward for the project. Let me know.

**Comment by mohits** [comment]
@MSP-Greg - I was able to get Ragel to work on Windows (see issue #63 on the repo). I also managed to identify why it was breaking (at least on my PC) and have also been able to fix issues #51 (and the related issue I created on #61 with Ruby 2.7) and there's a PR open for it so that it can work on Ruby 2.4+ up to Ruby 2.7.

I don't know how to set up CI for Windows, but I can at least do it manually on Ruby 2.7 on my side :)

**Comment by MSP-Greg** [comment]
@mohits

It's been a few months, but I did say "I've got passing tests on Travis for 1.9.3 thru 2.3, and Actions passing Ubuntu, macOS, & Windows with Ruby 2.4 thru 2.7."

At the time, the oldest Ruby available on Actions was 2.4, now it's 2.2.  So I can add current CI, make it work on Windows, etc.

I just wanted to test YARD locally and on Windows, and RedCloth stopped that.  But, I've never written a textile document nor do I consider myself a good c coder.  So, I'm not really interested in being a maintainer...

**Comment by mohits** [comment]
Hi, thanks for your comments in a couple of places. I am a C programmer and use Textile a lot - which is why I came looking for this (in fact, I was trying to get my Jekyll blog working - and that uses Textile). If you can help with CI, I can probably try to help with finding what's breaking the release. As it is, the gem is not updated in 4 years, so it is obviously working well for many people.

**Comment by MSP-Greg** [comment]
> If you can help with CI

Found the last CI from my fork:

https://github.com/MSP-Greg/redcloth/actions/runs/8097097

https://travis-ci.org/MSP-Greg/redcloth/builds/634425224

**Comment by MSP-Greg** [comment]
@mohits

> Hi, thanks for your comments in a couple of places. I am a C programmer and use Textile a lot

Ruby just changed master from 2.8.0 to 3.0.0, so I had to re-install all my gems.   I use Ruby master to generate https://msp-greg.github.io/ which is a YARD based doc site with Ruby and a bunch of repos/gems.  Forgot about the hacks I have in RedCloth for Windows.

Might you be willing to take on maintaining RedCloth?

I can help with CI and/or converting over to GH Actions if desired.

**Comment by jgarber** [comment]
@mohits @MSP-Greg I added you both to repo access in case you want to make a release with your changes. Sadly, it's been years since I even installed RedCloth, let alone worked on it.

**Comment by MSP-Greg** [comment]
@jgarber

Thanks, and no reason to say 'sadly'.  Thank you for your work on it.  Just compiled it with MinGW using gcc 10.2.0, so its stood the 'test of time'...  @mohits and I can clear up the Windows issues, and I'll see about getting CI running on Actions.

**Comment by mohits** [comment]
Thanks @jgarber  and @joshuasiler for stewarding the ship. I am happy to help.

@MSP-Greg - it's now in the middle of the work week, so I might get to this either later at night, or in the weekend. If I remember correctly, the update works fine on Windows with Ruby > 2.4 that tries to build the code and only has an issue with the load path for the DLL.

Last I remember, I was struggling with JRuby since some tests were failing relating to other charset support - that I intend to get back to but my Java skills are not great :)

I'm also between computers, so there's the slight additional in getting everything back up to where it used to be.

Best wishes!

**Comment by casperisfine** [comment]
Did anything happen here? I see @MSP-Greg is now Collaborator, however the gem owners didn't change so I assume no release is possible?

**Comment by heliocola** [comment]
I will close this issue as there has been a few releases already.
I reviewed all the issues linked and they are either closed, fixed, or merged.

If there is anything else still pending, please feel free to re-open it or open another issue.
